--EXCLUIR--
/*
DROP TABLE [nome_tabela]
DROP DATABASE [nome_database]
*/
DROP TABLE tb_Vendas

--REFATORANDO TABELAS--
CREATE TABLE tb_Vendas(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	IdCliente UNIQUEIDENTIFIER FOREIGN KEY REFERENCES tb_Clientes (Id) NOT NULL,
	DataVenda DATETIME NOT NULL,
)

CREATE TABLE tb_ProdutoVenda(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	IdVenda UNIQUEIDENTIFIER FOREIGN KEY REFERENCES tb_Vendas (Id) NOT NULL,
	IdProduto UNIQUEIDENTIFIER FOREIGN KEY REFERENCES tb_Produtos (Id) NOT NULL,
	QtdProduto INT NOT NULL
)